### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by lq782655835** [vusion/vusion-ui#1]
I'm not working to use vusion-ui, bellow is the detail error:

![image](https://user-images.githubusercontent.com/6310131/45615433-0f0ee180-ba9f-11e8-8311-3e095ba5c7bd.png)

* enviroment: MacOS 10.13.1
* project: vue-cli 3
* node: v10.10.0
* npm: 6.4.1

### restore this error:

1. vue-cli create test project
```
vue create vusion-ui-issue
```

2. add bellow code in mian.js
```
import Vue from 'vue'
import App from './App.vue'
import * as CloudUI from 'vusion-ui.vusion';
import { install } from 'vusion-utils';
install(CloudUI, Vue); // 全局注册组件库

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

this is full project for test [codepen](https://codepen.io/lq782655835/project/editor/DNNvOQ)

**Comment by z-ZYS-s** [comment]
Vusion UI cannot work with vue-cli 3 at present.
